unknown: bin
001_chips_can: long_table_a
002_master_chef_can: long_table_a
003_cracker_box: long_table_a
004_sugar_box: long_table_a
005_tomato_soup_can: long_table_a
006_mustard_bottle: long_table_a
007_tuna_fish_can: long_table_a
008_pudding_box: long_table_a
009_gelatin_box: long_table_a
010_potted_meat_can: long_table_a
011_banana: long_table_a
012_strawberry: long_table_a
013_apple: long_table_a
014_lemon: long_table_a
015_peach: long_table_a
016_pear: long_table_a
017_orange: long_table_a
018_plum: long_table_a
019_pitcher_base: long_table_a
021_bleach_cleanser: long_table_a
022_windex_bottle: long_table_a
023_wine_glass: long_table_a
024_bowl: long_table_a
025_mug: long_table_a
026_sponge: long_table_a
027-skillet: bin
028_skillet_lid: bin
029_plate: long_table_a
030_fork: long_table_a
031_spoon: long_table_a
032_knife: long_table_a
033_spatula: long_table_a
035_power_drill: bin
036_wood_block: bin
037_scissors: bin
038_padlock: bin
039_key: bin
040_large_marker: bin
041_small_marker: bin
042_adjustable_wrench: bin
043_phillips_screwdriver: bin
044_flat_screwdriver: bin
046_plastic_bolt: bin
047_plastic_nut: bin
048_hammer: bin
049_small_clamp: bin
050_medium_clamp: bin
051_large_clamp: bin
052_extra_large_clamp: bin
053_mini_soccer_ball: bin
054_softball: bin
055_baseball: bin
056_tennis_ball: bin
057_racquetball: bin
058_golf_ball: bin
059_chain: bin
061_foam_brick: bin
062_dice: bin
063-a_marbles: bin
065-a_cups: bin
070-a_colored_wood_blocks: bin
071_nine_hole_peg_test: bin
072-a_toy_airplane: bin
073-a_lego_duplo: bin
076_timer: bin
077_rubiks_cube: bin
