001_chips_can: long_table_a
002_master_chef_can: long_table_a
003_cracker_box: long_table_a
004_sugar_box: long_table_a
005_tomato_soup_can: long_table_a
006_mustard_bottle: long_table_a
007_tuna_fish_can: long_table_a
008_pudding_box: long_table_a
009_gelatin_box: long_table_a
010_potted_meat_can: long_table_a
011_banana: long_table_a
012_strawberry: long_table_a
013_apple: long_table_a
014_lemon: long_table_a
015_peach: long_table_a
016_pear: long_table_a
017_orange: long_table_a
018_plum: long_table_a
019_pitcher_base: long_table_a
021_bleach_cleanser: long_table_a
022_windex_bottle: long_table_a
023_wine_glass: long_table_a
024_bowl: long_table_a
025_mug: long_table_a
026_sponge: long_table_a
027-skillet: box
028_skillet_lid: box
029_plate: long_table_a
030_fork: long_table_a
031_spoon: long_table_a
032_knife: long_table_a
033_spatula: long_table_a
035_power_drill: box
036_wood_block: box
037_scissors: box
038_padlock: box
039_key: box
040_large_marker: box
041_small_marker: box
042_adjustable_wrench: box
043_phillips_screwdriver: box
044_flat_screwdriver: box
046_plastic_bolt: box
047_plastic_nut: box
048_hammer: box
049_small_clamp: box
050_medium_clamp: box
051_large_clamp: box
052_extra_large_clamp: box
053_mini_soccer_ball: box
054_softball: box
055_baseball: box
056_tennis_ball: box
057_racquetball: box
058_golf_ball: box
059_chain: box
061_foam_brick: box
062_dice: box
063-a_marbles: box
065-a_cups: box
070-a_colored_wood_blocks: box
071_nine_hole_peg_test: box
072-a_toy_airplane: box
073-a_lego_duplo: box
076_timer: box
077_rubiks_cube: box
