# Description: Defines a state machine for a World Robot Summit Tidy Up task
# Author: Alex Mitrevski
# Email: aleksandar.mitrevski@h-brs.de
sm_id: mdr_wrs_tidy_up
states: [INITIALISE_SCENARIO, CHECK_TIDYING_DONE, SELECT_SCANNING_POSE, GO_TO_SCANNING_POSE, FIND_OBJECTS, SELECT_OBJECT_FOR_PICKING, PICKUP_OBJECT, MOVE_TO_STORAGE_LOCATION, THROW_OBJECT, INITIALISE_OBSTACLE_REMOVAL, GO_TO_SECOND_ROOM_CORRIDOR, FIND_FLOOR_OBSTACLES, SELECT_OBSTACLE_FOR_PICKING, PICKUP_OBSTACLE, MOVE_TO_BOX, THROW_OBSTACLE]
outcomes: [DONE, TIMEOUT, FAILED]
state_descriptions:
    # Task 1: Cleaning up objects
    - state:
        name: INITIALISE_SCENARIO
        state_module_name: mdr_wrs_tidy_up.scenario_states.initialise_scenario
        state_class_name: InitialiseScenario
        transitions:
            - transition:
                name: succeeded
                state: SELECT_SCANNING_POSE
        arguments:
            - argument:
                name: floor_objects_cleared
                value:
                    table_inspection_area1: false
                    table_inspection_area2: false
                    table_inspection_area3: false
            - argument:
                name: table_objects_cleared
                value:
                    long_table_b: false
                    tall_table: false
    - state:
        name: CHECK_TIDYING_DONE
        state_module_name: mdr_wrs_tidy_up.scenario_states.check_tidying_done
        state_class_name: CheckTidyingDone
        transitions:
            - transition:
                name: room_not_clear
                state: SELECT_SCANNING_POSE
            - transition:
                name: room_clear
                state: INITIALISE_OBSTACLE_REMOVAL
    - state:
        name: SELECT_SCANNING_POSE
        state_module_name: mdr_wrs_tidy_up.scenario_states.select_scanning_pose
        state_class_name: SelectScanningPose
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_SCANNING_POSE
            - transition:
                name: failed
                state: SELECT_SCANNING_POSE
        arguments:
            - argument:
                name: floor_scanning_poses
                value: [table_inspection_area1, table_inspection_area2, table_inspection_area3]
            - argument:
                name: table_scanning_poses
                value: [long_table_b, tall_table]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: GO_TO_SCANNING_POSE
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: FIND_OBJECTS
            - transition:
                name: failed
                state: GO_TO_SCANNING_POSE
            - transition:
                name: failed_after_retrying
                state: SELECT_SCANNING_POSE
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: FIND_OBJECTS
        state_module_name: mdr_wrs_tidy_up.scenario_states.find_objects
        state_class_name: FindObjects
        transitions:
            - transition:
                name: succeeded
                state: SELECT_OBJECT_FOR_PICKING
            - transition:
                name: no_obstacles
                state: SELECT_SCANNING_POSE
            - transition:
                name: failed
                state: FIND_OBJECTS
            - transition:
                name: failed_after_retrying
                state: SELECT_SCANNING_POSE
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: SELECT_OBJECT_FOR_PICKING
        state_module_name: mdr_wrs_tidy_up.scenario_states.select_object_for_picking
        state_class_name: SelectObjectForPicking
        transitions:
            - transition:
                name: succeeded
                state: PICKUP_OBJECT
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: PICKUP_OBJECT
        state_module_name: mdr_wrs_tidy_up.scenario_states.pickup_object
        state_class_name: PickupObject
        transitions:
            - transition:
                name: succeeded
                state: MOVE_TO_STORAGE_LOCATION
            - transition:
                name: failed
                state: PICKUP_OBJECT
            - transition:
                name: failed_after_retrying
                state: GO_TO_SCANNING_POSE
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: MOVE_TO_STORAGE_LOCATION
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: THROW_OBJECT
            - transition:
                name: failed
                state: MOVE_TO_STORAGE_LOCATION
            - transition:
                name: failed_after_retrying
                state: MOVE_TO_STORAGE_LOCATION
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: THROW_OBJECT
        state_module_name: mdr_manipulation_behaviours.throw_object_in
        state_class_name: ThrowObjectIn
        transitions:
            - transition:
                name: succeeded
                state: CHECK_TIDYING_DONE
            - transition:
                name: failed
                state: THROW_OBJECT
            - transition:
                name: failed_after_retrying
                state: CHECK_TIDYING_DONE
        arguments:
            - argument:
                name: number_of_retries
                value: 3

    # Task 2a: Going to the second room
    - state:
        name: INITIALISE_OBSTACLE_REMOVAL
        state_module_name: mdr_wrs_tidy_up.scenario_states.initialise_scenario
        state_class_name: InitialiseScenario
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_SECOND_ROOM_CORRIDOR
        arguments:
            - argument:
                name: object_location
                value: floor
    - state:
        name: GO_TO_SECOND_ROOM_CORRIDOR
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: FIND_FLOOR_OBSTACLES
            - transition:
                name: failed
                state: GO_TO_SECOND_ROOM_CORRIDOR
            - transition:
                name: failed_after_retrying
                state: GO_TO_SECOND_ROOM_CORRIDOR
        arguments:
            - argument:
                name: destination_locations
                value: [second_room_corridor]
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: FIND_FLOOR_OBSTACLES
        state_module_name: mdr_wrs_tidy_up.scenario_states.find_objects
        state_class_name: FindObjects
        transitions:
            - transition:
                name: succeeded
                state: SELECT_OBSTACLE_FOR_PICKING
            - transition:
                name: no_obstacles
                state: DONE
            - transition:
                name: failed
                state: GO_TO_SECOND_ROOM_CORRIDOR
            - transition:
                name: failed_after_retrying
                state: GO_TO_SECOND_ROOM_CORRIDOR
        arguments:
            - argument:
                name: object_detection_server_name
                value: /mas_perception/detect_objects
            - argument:
                name: cloud_obstacle_detection_topic
                value: /mas_perception/cloud_obstacle_detection/obstacle_objects
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: SELECT_OBSTACLE_FOR_PICKING
        state_module_name: mdr_wrs_tidy_up.scenario_states.select_object_for_picking
        state_class_name: SelectObjectForPicking
        transitions:
            - transition:
                name: succeeded
                state: PICKUP_OBSTACLE
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: PICKUP_OBSTACLE
        state_module_name: mdr_wrs_tidy_up.scenario_states.pickup_object
        state_class_name: PickupObject
        transitions:
            - transition:
                name: succeeded
                state: MOVE_TO_BOX
            - transition:
                name: failed
                state: PICKUP_OBSTACLE
            - transition:
                name: failed_after_retrying
                state: GO_TO_SECOND_ROOM_CORRIDOR
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: MOVE_TO_BOX
        state_module_name: mdr_navigation_behaviours.move_base
        state_class_name: MoveBase
        transitions:
            - transition:
                name: succeeded
                state: THROW_OBSTACLE
            - transition:
                name: failed
                state: MOVE_TO_BOX
            - transition:
                name: failed_after_retrying
                state: MOVE_TO_BOX
        arguments:
            - argument:
                name: number_of_retries
                value: 3
    - state:
        name: THROW_OBSTACLE
        state_module_name: mdr_manipulation_behaviours.throw_object_in
        state_class_name: ThrowObjectIn
        transitions:
            - transition:
                name: succeeded
                state: GO_TO_SECOND_ROOM_CORRIDOR
            - transition:
                name: failed
                state: THROW_OBSTACLE
            - transition:
                name: failed_after_retrying
                state: GO_TO_SECOND_ROOM_CORRIDOR
        arguments:
            - argument:
                name: number_of_retries
                value: 3

    # TODO: Add states for Task 2b: Delivering an object to a person
